Added output log to the function SplitAndPay.
71ae/SplitMiningRewards pull request #20
Opened 2020-03-17 17:02 UTC by homo-cogitabundus

The only logging method I found that I managed to implement was emitting events.
This branch currently uses two different implementations of events for logging.

In all cases except in the SplitAndPay function, the event emitted contains several parameters, which take the form of a sequence of pairs of parameters where each pair provides information about a single entity. The first parameter of each pair is a string that describes the meaning of the entity, explaining what it is, while the second parameter is either a uint or an address which contains the actual value of the entity.
    e.g: event Log(string message, address a1);
           The parameter message describes the meaning of the parameter a1. For example, the parameter message might be "Beneficiary changed to: " to explain what the parameter address is.

In the log event used by the SplitAndPay function, the string parameters do not exist:
    event LogSplitting(uint Donated, uint Sent_to_costcentre, uint Remainder);
 Instead, the meaning of the value parameters is described by the variable names of those parameters. Since the Remix output displays the names of the parameters alongside their values, this works fine, but I'm not sure if we will be able to see the variable names in the real implementation of the contract. This is therefore a point to observe when testing this contract on a small network, to see which logging method is the most suitable.

2020-03-29 13:36 UTC, 71ae requested changes

2020-03-29 13:36 UTC, 71ae commented on SplitMiningRewards.sol
> +        costcenter.transfer(electricity_cost); // sending the costcenter the money to cover the electricity costs
You are now (trying to) sending the value of electricity_cost, even if there isn't enough money to cover them all.
Want to use `sent_electricity_cost` variable for the transfer, instead?

2020-03-30 04:43 UTC, homo-cogitabundus commented
Yep, thanks. That's what I meant! I obviously need to be more careful when proof reading. I also still need to do a thorough test of all possible situations.

Sent from ProtonMail mobile

-------- Original Message --------
On 29 Mar 2020 15:36, Andreas E. wrote:

> @71ae requested changes on this pull request.
>
> ---------------------------------------------------------------
>
> In [SplitMiningRewards.sol](https://github.com/71ae/SplitMiningRewards/pull/20#discussion_r399798837):
>
>>          else // there is not enough money in this wallet to cover all the electricity costs
> -            costcenter.transfer(_balance - transaction_fee);   // sending the costcenter all the money in this account
> +            sent_electricity_costs = _balance - transaction_fee;   // sending the costcenter all the money in this account
> +        costcenter.transfer(electricity_cost); // sending the costcenter the money to cover the electricity costs
>
> You are now (trying to) sending the value of electricity_cost, even if there isn't enough money to cover them all.
> Want to use sent_electricity_cost variable for the transfer, instead?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, [view it on GitHub](https://github.com/71ae/SplitMiningRewards/pull/20#pullrequestreview-383412136), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AOKGHLWVNADMUL4QWLXRLJLRJ5FGVANCNFSM4LNUNC2Q).

2020-03-30 05:51 UTC, homo-cogitabundus commented
Hang on, there's something wrong here.
costcenter.transfer(balance - transactionfee)
The above line shouldn't exist because it's job is performed by costcenter.transact(sent_electricity_costs)
I'll have to check I uploaded the final finished version of my work to the pull request , cause I can't imagine I left a mistake as big as that in!

Sent from ProtonMail mobile

-------- Original Message --------
On 29 Mar 2020 15:36, Andreas E. wrote:

> @71ae requested changes on this pull request.
>
> ---------------------------------------------------------------
>
> In [SplitMiningRewards.sol](https://github.com/71ae/SplitMiningRewards/pull/20#discussion_r399798837):
>
>>          else // there is not enough money in this wallet to cover all the electricity costs
> -            costcenter.transfer(_balance - transaction_fee);   // sending the costcenter all the money in this account
> +            sent_electricity_costs = _balance - transaction_fee;   // sending the costcenter all the money in this account
> +        costcenter.transfer(electricity_cost); // sending the costcenter the money to cover the electricity costs
>
> You are now (trying to) sending the value of electricity_cost, even if there isn't enough money to cover them all.
> Want to use sent_electricity_cost variable for the transfer, instead?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, [view it on GitHub](https://github.com/71ae/SplitMiningRewards/pull/20#pullrequestreview-383412136), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AOKGHLWVNADMUL4QWLXRLJLRJ5FGVANCNFSM4LNUNC2Q).

2020-03-30 07:38 UTC, 71ae commented
> Yep, thanks. That's what I meant! I obviously need to be more careful when proof reading. I also still need to do a thorough test of all possible situations. 

No worries, that's why pull-requests and reviews are being done.

2020-03-30 13:08 UTC, homo-cogitabundus commented
Never mind about that last comment, I was viewing the comments on my email client and didn't see that that line was marked as removed.

Sent from ProtonMail mobile

-------- Original Message --------
On 30 Mar 2020 07:51, homo cogitabundus wrote:

> Hang on, there's something wrong here.
> costcenter.transfer(balance - transactionfee)
> The above line shouldn't exist because it's job is performed by costcenter.transact(sent_electricity_costs)
> I'll have to check I uploaded the final finished version of my work to the pull request , cause I can't imagine I left a mistake as big as that in!
>
> Sent from ProtonMail mobile
>
> -------- Original Message --------
> On 29 Mar 2020 15:36, Andreas E. wrote:
>
>> @71ae requested changes on this pull request.
>>
>> ---------------------------------------------------------------
>>
>> In [SplitMiningRewards.sol](https://github.com/71ae/SplitMiningRewards/pull/20#discussion_r399798837):
>>
>>>          else // there is not enough money in this wallet to cover all the electricity costs
>> -            costcenter.transfer(_balance - transaction_fee);   // sending the costcenter all the money in this account
>> +            sent_electricity_costs = _balance - transaction_fee;   // sending the costcenter all the money in this account
>> +        costcenter.transfer(electricity_cost); // sending the costcenter the money to cover the electricity costs
>>
>> You are now (trying to) sending the value of electricity_cost, even if there isn't enough money to cover them all.
>> Want to use sent_electricity_cost variable for the transfer, instead?
>>
>> —
>> You are receiving this because you were assigned.
>> Reply to this email directly, [view it on GitHub](https://github.com/71ae/SplitMiningRewards/pull/20#pullrequestreview-383412136), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AOKGHLWVNADMUL4QWLXRLJLRJ5FGVANCNFSM4LNUNC2Q).

2020-03-31 18:35 UTC, 71ae approved these changes

2020-04-01 18:03 UTC, merged